### PR TITLE
Update postcss to 8.x and postcss-scss to 3.x.

### LINKED ISSUE #94: Update to postcss 8.x, postcss-scss 3.x

### PR DESCRIPTION
**Pull request by XhmikosR**
Closes #92, closes #93, closes #94

I'm not sure if we are supposed to move postcss to peer dependencies, but then we also have postcss-scss.

### CODE REVIEW

**Comment by Johann-S** [comment]
We required them directly here: https://github.com/XhmikosR/find-unused-sass-variables/blob/master/lib/parse-variable.js#L3-L5
so we should kept them as deps.

BTW it seems to work pretty fine, am I wrong ?

**Comment by XhmikosR** [comment]
Indeed, it does seem to work well hence why I made the PR. I'd like to
update commander too before making a new release since it will be a major
version. If you have time please have a look :)

**Comment by XhmikosR** [comment]
Here is the migration guide: https://evilmartians.com/chronicles/postcss-8-plugin-migration

@Johann-S can you have a look please? :) We can still keep postcss as a dependency, though.

**Comment by Johann-S** [comment]
this article doesn't concerns us because `fusv` isn't a PostCSS plugin

**Comment by XhmikosR** [comment]
We do use internal APIs, don't we? https://github.com/XhmikosR/find-unused-sass-variables/blob/bee52fff30e66e2f6dc71b6eb93e4bafadf580b3/lib/parse-variable.js#L4-L5

Either way, I just want to make sure we aren't missing something :) postcss-scss doesn't seem to have any new API AFAICT.

**Comment by Johann-S** [comment]
Yep but not as a plugin, and we import those just to be sure what kind of object we deal with

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
