### PR TITLE
Use Ora

### PR DESCRIPTION
**Pull request by Johann-S**
Trying to add Ora but I don't see any spinner here :worried:

### CODE REVIEW

**Comment by XhmikosR** [comment]
Yup, same here :/ I think it's because we don't use promises maybe?

**Comment by XhmikosR** [comment]
I already had https://github.com/XhmikosR/find-unused-sass-variables/compare/xmr-ora but has the same issue.

**Comment by Johann-S** [comment]
I think maybe it's because our script is to fast to let us see the spinner

**Comment by XhmikosR** [comment]
I've been testing locally with huge input and I only see a static blue `i`.

**Comment by Johann-S** [comment]
yep I tested that now I added a `setTimeout` with 1000 ms and I'm able to see the spinner

**Comment by Johann-S** [comment]
I don't understand your problem see my gif : 

gif

everything is fine with a setTimeout

**Comment by XhmikosR** [comment]
For one, you are using MSYS. With plain cmd, the spinner just shows a blue, illegible `i`. Second, the spinner doesn't spin.

Again, I'm using Windows built-in cmd, which you should also use.

**Comment by Johann-S** [comment]
I don't like Windows built-in cmd it hurts my eyes :laughing:

**Comment by XhmikosR** [comment]
Yeah, but it doesn't work. Nor does it work with mintty.

**Comment by Johann-S** [comment]
It works on my Windows cmd built-in but maybe I have something in my PATH which make it works

**Comment by XhmikosR** [comment]
My dev VM is on Windows 7, so maybe that has something to do too.

The fact is that there, I don't see the spinner spinning, and also the spinner has a blue color which is illegible.

I can't capture a video to show you that the spinner doesn't spin

cmd

**Comment by Johann-S** [comment]
I'm not on a VM but I have a Win7 too

**Comment by XhmikosR** [comment]
Can you post a video with the built-in cmd?

**Comment by Johann-S** [comment]
gif

**Comment by XhmikosR** [comment]
Something weird happens with your cmd. I'll see if I can pinpoint the cause
otherwise if it works for you I guess we can merge later.

**Pull request merged**
