### PR TITLE
Replace glob with totalist

### PR DESCRIPTION
**Pull request by XhmikosR**
@GeoSot File extensions are broken right now, any help is welcome since I don't quite get that join `|` magic :)

### CODE REVIEW

**Comment by GeoSot** [comment]
Do we need to replace 1 line of `glob` usage, with 4 lines that  `totalist ` needs,  for a special reason? It provides better speed or something?

**Comment by XhmikosR** [comment]
Yup, it's smaller and probably faster too :) Our lines added here don't matter a lot IMHO.

I just don't get that `|` magic. Couldn't we just loop or something similar?

**Comment by XhmikosR** [comment]
OK, I think I got it right now. Let me know what do you think @GeoSot :)

**Comment by GeoSot** [comment]
Without having any reason to go against, I suppose is fine. 
However, for sure `glob` will already exist on any possible node installation (so it is not matter of size), and it does by itself the filtering we need, so if we don't have any justified speed comparison, indicating a serious difference, I wouldn't choose this solution

**Comment by XhmikosR** [comment]
TBH, I stopped caring about the fact that a dependency might be in the dependencies tree already.

Sure, people used and still use glob because it sort of became a tradition in the early Node.js years.

I certainly prefer smaller, faster packages to depend on nowadays :)

That being said, I will think about it, but the previous solution with the file extensions was bad, so I might change that regardless, in another PR.

My only concern with the totalist solution is the small code duplication.

I have also made a branch which adds `ignoredFiles` support https://github.com/XhmikosR/find-unused-sass-variables/compare/xmr/rm-glob...xmr/ignoredFiles

**Pull request closed without merging**
